/**
 * Generates the app icon, Android adaptive icon and splash artwork.
 *
 * Kept as a script rather than checked-in binaries alone, so the mark can be
 * regenerated when the palette changes. Run with `npm run assets`.
 *
 * The mark: a document corner with a downward arrow compressing toward a
 * baseline — "make this file smaller" without a single word of text, which
 * matters for an app used in two languages.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const ASSET_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', 'assets');

const INK = '#FBF8F3';
const BRAND = '#9B2C1E';
const BRAND_DEEP = '#6E1C12';

/** The logo mark on a transparent background, sized to a square canvas. */
function markSvg(size: number, inset: number): string {
  const s = size;
  const pad = s * inset;
  const w = s - pad * 2;
  // Document body, sitting in the upper half so the arrow has clear air below.
  const docX = pad + w * 0.26;
  const docY = pad + w * 0.03;
  const docW = w * 0.48;
  const docH = w * 0.38;
  const fold = w * 0.14;
  // Arrow: starts below the document, never crosses it. The shaft needs real
  // length or the head reads as a loose triangle at launcher size.
  const arrowCx = pad + w * 0.5;
  const arrowTop = docY + docH + w * 0.07;
  const arrowBottom = pad + w * 0.8;
  const headHalf = w * 0.11;
  // The baseline the arrow compresses onto.
  const baseY = pad + w * 0.88;

  return `<svg width="${s}" height="${s}" viewBox="0 0 ${s} ${s}" xmlns="http://www.w3.org/2000/svg">
  <g fill="none" stroke="${INK}" stroke-linecap="round" stroke-linejoin="round" stroke-width="${w * 0.055}">
    <path d="M ${docX} ${docY + docH}
             L ${docX} ${docY}
             L ${docX + docW - fold} ${docY}
             L ${docX + docW} ${docY + fold}
             L ${docX + docW} ${docY + docH}
             Z" />
    <path d="M ${docX + docW - fold} ${docY} L ${docX + docW - fold} ${docY + fold} L ${docX + docW} ${docY + fold}" />
    <path d="M ${docX + w * 0.07} ${docY + docH * 0.58} L ${docX + docW - w * 0.07} ${docY + docH * 0.58}" />
    <path d="M ${docX + w * 0.07} ${docY + docH * 0.8} L ${docX + docW - w * 0.18} ${docY + docH * 0.8}" />
  </g>
  <g fill="${INK}">
    <rect x="${arrowCx - w * 0.035}" y="${arrowTop}" width="${w * 0.07}" height="${arrowBottom - arrowTop - headHalf}" rx="${w * 0.035}" />
    <path d="M ${arrowCx - headHalf} ${arrowBottom - headHalf}
             L ${arrowCx + headHalf} ${arrowBottom - headHalf}
             L ${arrowCx} ${arrowBottom + headHalf * 0.5} Z" />
    <rect x="${pad + w * 0.24}" y="${baseY}" width="${w * 0.52}" height="${w * 0.055}" rx="${w * 0.0275}" />
  </g>
</svg>`;
}

function backgroundSvg(size: number): string {
  return `<svg width="${size}" height="${size}" viewBox="0 0 ${size} ${size}" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="g" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="${BRAND}" />
      <stop offset="100%" stop-color="${BRAND_DEEP}" />
    </linearGradient>
  </defs>
  <rect width="${size}" height="${size}" fill="url(#g)" />
</svg>`;
}

async function renderSquare(path: string, size: number, inset: number, withBackground: boolean) {
  const layers: sharp.OverlayOptions[] = [{ input: Buffer.from(markSvg(size, inset)) }];
  const base = withBackground
    ? sharp(Buffer.from(backgroundSvg(size)))
    : sharp({
        create: {
          width: size,
          height: size,
          channels: 4,
          background: { r: 0, g: 0, b: 0, alpha: 0 },
        },
      });
  await base.composite(layers).png().toFile(path);
}

async function renderSplash(path: string, width: number, height: number) {
  const markSize = Math.round(Math.min(width, height) * 0.34);
  const mark = await sharp(Buffer.from(markSvg(markSize, 0.08))).png().toBuffer();
  await sharp({
    create: {
      width,
      height,
      channels: 4,
      background: { r: 155, g: 44, b: 30, alpha: 1 },
    },
  })
    .composite([{ input: mark, gravity: 'centre' }])
    .png()
    .toFile(path);
}

async function main(): Promise<void> {
  await mkdir(ASSET_DIR, { recursive: true });

  // Store icon and launcher icon: mark on the brand gradient.
  await renderSquare(join(ASSET_DIR, 'icon.png'), 1024, 0.18, true);
  // Android adaptive foreground: transparent, extra inset because the system
  // masks and scales it (only the middle ~66% is reliably visible).
  await renderSquare(join(ASSET_DIR, 'adaptive-icon.png'), 1024, 0.28, false);
  // Favicon for the web build.
  await renderSquare(join(ASSET_DIR, 'favicon.png'), 64, 0.16, true);
  await renderSplash(join(ASSET_DIR, 'splash.png'), 1284, 2778);

  await writeFile(
    join(ASSET_DIR, 'README.md'),
    'Generated by `npm run assets` (scripts/makeAssets.ts). Do not edit by hand.\n',
  );
  console.log(`Wrote icon.png, adaptive-icon.png, favicon.png and splash.png to ${ASSET_DIR}`);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
